<a href="https://colab.research.google.com/github/LPolyakova/Linear_Algebra_for_CS_students/blob/main/Colab_templates/LA_COLAB_01_TEMPLATE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **ЛА_COLAB_01: інструменти лінійної алгебри**

**Ім'я Прізвище, група**

В цьому колабі треба продемонструвати виконання завдань з таких тем: **Матриці, Системи лінійних рівнянь, Визначники.**

З кожної теми ви маєте обрати одну із двох запропонованих задач. Будь ласка, залиште всі комірки обраної задачі на місці --  не видаляйте їх, навіть, якщо ви не зробили якийсь з пунктів. Лише пишіть розв'язки у вказаних місцях:

✔️ *Запишіть міркування тут* -- для міркувань, тексту, формул. Не вставляйте фото рукописного тексту в ці комірки, пишіть текст і формули у форматі $\TeX$;

`# write your code here` -- для коду.

Комірки іншої задачі з кожної теми (ту, що ви її не обирали) треба видалити.

Також, будь ласка, не видаляйте комірки, що призначені для коментарів викладача

<font color="red"> *Коментар викладача:* <font>



Користуватись ресурсами з інтернету або штучним інтелектом не заборонено. Однак, якщо ви використовуєте ШІ, код, довідкові матеріали з інтернету або літератури, ОБОВ'ЯЗКОВО вказуйте посилання на ці ресурси в коментарях у комірках, де ці ресурси використовуються.

Зокрема, усі шматки коду, які були згенеровані за допомогою ШІ, мають бути помічені:
`# generated by AI `
або аналогічним чином. Бажано також вказувати модель, яку ви використовували.

Також ви повинні розібратися в усьому, що використовували, і бути в змозі відповідати на питання, які стосуються всього, що є у вашій роботі, зокрема, всіх понять, що виникають у задачах.

Виконувати завдання слід САМОСТІЙНО. У разі виявлення однакових розв'язків роботи можуть бути анульовані!

Необхідні імпорти вказано в преамбулі. Імпортувати інші пакети (наприклад, для візуалізації), дозволяється за згодою з викладачем

📕 [Довідник з Markdown](https://www.markdownguide.org
) (для набору та форматування тексту в текстових комірках)

📕 [Короткий довідник набору формул у TeX](https://ru.wikibooks.org/wiki/%D0%9C%D0%B0%D1%82%D0%B5%D0%BC%D0%B0%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B5_%D1%84%D0%BE%D1%80%D0%BC%D1%83%D0%BB%D1%8B_%D0%B2_LaTeX)

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import networkx as nx
import pandas as pd
from scipy import linalg
import sympy

## Задача 1: матриці

Оберіть і розв'яжіть одну із задач 1.1 або 1.2 на ваш вибір. Іншу задачу видаліть з шаблону.

🧩 **1.1. Лінійні рекурентні співвідношення**

Числа Фібоначчі -- це послідовність чисел $F_n$, заданих умовами $F_0=0, F_1=1$, а далі $F_{n+1} = F_n+F_{n-1}$ для кожного $n>1$.

Для обчислення чисел Фібоначчі  можна скористатися не лише традиційним, але й матричним способом.

Розглянемо матрицю $M = \left(\begin{array}{cc}
		1 & 1  \\
		1 & 0
	\end{array}
	\right) $.
Тоді  $\left(\begin{array}{c}
		F_{n+1}   \\
		F_{n}  
	\end{array}
	\right) = M \left(\begin{array}{c} F_{n}   \\ F_{n-1}  \end{array} \right) $.


1️⃣ Доведіть методом мат. індукції, що $\left(\begin{array}{c}
F_{n+1} \\
F_{n}
\end{array}
\right) = M^n \left(\begin{array}{c} 1 \\ 0 \end{array} \right) $.
    
Тобто для обчислення $n$ -го і $n + 1$ -го чисел Фібоначчі достатньо обчислити $n$ -ий степінь матриці $M$ і помножити на вектор початкових значень.

✔️ *Ваші міркування запишіть тут.*

2️⃣ Розгляньте узагальнення цієї ситуації. Нехай задано лінійне рекурентне співвідношення $c_n = \alpha_1 c_{n-1}+\alpha_2 c_{n-2}+\dots +\alpha_kc_{n-k}$ з числовими коефіцієнтами $\alpha_j$ та набір початкових значень $c_0, c_1 , \dots, c_{k-1}$.


Напишіть та протестуйте дві функції:

1. Перша функція за заданим списком коефіцієнтів $\alpha_j (j = 1, \dots k)$, списком початкових значень $c_j (j = 0, \dots k-1)$ і номером елемента $n$ обчислює $c_n$ за допомогою рекурсії (подумайте, як  раціонально реалізувати рекурсію).

2. Друга функція за заданим списком коефіцієнтів $\alpha_j (j = 1, \dots k)$, списком початкових значень $c_j (j = 0, \dots k-1)$ і номером елемента $n$ обчислює $c_n$ з за допомогою множення матриць (подумайте, як швидко обчислювати степінь матриці).

In [ ]:
#write your code here

3️⃣ Порівняйте швидкодію функцій:

1) теоретично, тобто оцініть складності реалізованих алгоритмів;

2) фактично, тобто заміряйте час обчислення кожної функції за допомогою %timeit;

3) розгляньте залежність часу обчислення кожної функції від $n$, $k$, проілюструйте графіками;

4) опишіть знайдені закономірності.

✔️ *Ваші міркування запишіть тут.*

In [ ]:
#write your code here

<font color="red"> *Коментар викладача:* <font>

🧩 **1.2. Оцінки складності**

У цій задачі ви будете досліджувати складність виконання дій над матрицями та векторами, тобто кількість операцій, що їх необхідно виконати, щоб отримати результат в залежності від вхідних розмірів матриць.

Як одиницю кількості операцій ми будемо розглядали так званий flop (FLoating-point OPeration). 1 flop -- це одна арифметична операція (додавання, віднімання, множення, ділення) над двома числами, записаними у форматa floating point. Швидкість виконання операцій комп'ютером, зазвичай, вимірюється у Gflop/s (гіга-flop за секунду), тобто скільки мільярдів ($10^9$) операцій в секунду здатен робити комп'ютер.

Наприклад, щоб знайти скалярний добуток двох $n$-векторів $u^tv=u_1v_1+\dots +u_nv_n$, треба виконати $n$ множень та $n-1$ додавання, тобто складність обчислення скалярного добутку двох $n$-векторів дорівнює $(2n-1)$ flop. Часто, порівняно незначні члени виразів опускають. Наприклад, для скалярного добутку, вважають, що складність його обчислення дорівнює приблизно $2n$ flop.

1️⃣ Знайдіть складність обчислення добутку $m\times n$ матриці $A$ на $n$-вектор $x$.

1) Якщо множити способом "рядок на стовпчик";
2) Якщо знаходити лінійну комбінацію стовпчиків матриці  $A$.

Порівняйте складності двох способів.

✔️ *Ваші міркування запишіть тут.*

2️⃣ Знайдіть складність обчислення добутку двох квадратних матриць порядку $n$ для кожного з чотирьох способів множення матриць ("рядок на стовпчик", "рядками", "стовпчиками", "стовпчик на рядок"). Порівняйте.

✔️ *Ваші міркування запишіть тут.*

3️⃣ Реалізуйте 4 способи множення матриць. Протестуйте, скільки часу витрачає кожен спосіб множення матриць. Для тестування можна побудувати випадкові матриці (наприклад, за допомогою np.random) досить великого порядку, для вимірювання часу можна використати функцію %timeit.
Порівняйте теоретичні розрахунки з виміряними фактично.

In [ ]:
#write your code here

<font color="red"> *Коментар викладача:* <font>

## Задача 2: системи лінійних рівнянь

Оберіть і розв'яжіть одну із задач 2.1 або 2.2 на ваш вибір. Іншу задачу видаліть з шаблону.

🧩 **2.1. Взаємодія галузей економіки**

1️⃣  У цій задачі за допомогою систем лінійних рівнянь ми будемо досліджувати, як впливає зміна потреб у тих чи інших ресурсах на виробництво цих ресурсів.
Припустимо ми маємо дві галузі економіки (наприклад, виробництво сталі $B_1$, та виробництво автомобілей $B_2$). Кожна з цих галузей $B_i$ виробляє продукцію, яку споживають: вона сама ($d_{ii}$), друга з розгляданих галузей ($d_{ij}$), а також інші галузі економіки ($d_{i0}$). Наприклад, за означеними галузями у деякому році спостерігається ситуація, наведена в таблиці нижче. До речі, ці дані наведено щодо економіки США за 1958 рік у млн.дол. зі статті нобелівського лауреата з економіки Василя Леонтьєва: Wassily W. Leontief, The Structure of the U.S. Economy, Scientific
American, volume 212 number 4 (Apr. 1965), p. 2. Запропонована модель галузей економіки, відома також як *input-output model* або *модель міжгалузевого балансу*, також належить йому.

In [ ]:
df_economy = pd.DataFrame(columns = ['branch', 'B1_consumption', 'B2_consumption', 'other_consumption', 'total'])
df_economy['branch'] = ['B1', 'B2']
df_economy['B1_consumption'] = [5395, 48]
df_economy['B2_consumption'] = [2664, 9030]
df_economy['other_consumption'] = ['', '']
df_economy['total'] = [25448, 30346]
df_economy

branch  B1_consumption  B2_consumption other_consumption  total
0     B1            5395            2664                    25448
1     B2              48            9030                    30346

З цієї таблиці, зокрема можна довідатися, що сталеливарна промисловість споживає власної продукції на суму $d_{11} = 5395$ млн. дол., а автомобілебудування споживає сталі на суму $d_{12} = 2664$ млн. дол. Також, знаючи загальний обсяг виробництва сталі $D_1=25448$, можна  розрахувати скільки сталі споживають інші галузі економіки (зокрема й іде на експорт, або залишається на складах): $d_{10}=D_1-d_{11}-d_{12}$. Зробіть це для обох галузей $B_1$, $B_2$ й запишіть результати у стовпчик 'other_consumption'.   

In [ ]:
#write your code here
#df_economy['other_consumption'] =
#df_economy

Нехай ми маємо прогноз щодо того, як зміниться споживання сталі та авто зовнішніми споживачами ('other\_consumption') на наступний рік:

$d'_{10} =d_{10} +\Delta _{1}$, $d'_{20} =d_{20} +\Delta _{2}$, $\Delta _{1} =200$, $\Delta _{2} =-25$. Тобто споживання сталі зовнішніми споживачами зросте на 200 млн. дол., а споживання авто зменшиться на 25 млн. дол.

Наша мета розрахувати, скільки сталі та авто має вироблятися для того, щоб задовольнити усі потреби, зважаючи на передбачувані зміни у споживанні.

Для цього ми запишемо умови, що пов'язують усі наведені та шукані величини.

Споживання цього року (значення всіх величин нам відомі з таблиці) задається системою умов:

${\displaystyle \begin{cases}
D_{1} =d_{11} +d_{12} +d_{10} ;\\
D_{2} =d_{21} +d_{22} +d_{20}
\end{cases}}$



Споживання наступного року:



${\displaystyle \begin{cases}
D'_{1} =d'_{11} +d'_{12} +d'_{10} ;\\
D'_{2} =d'_{21} +d'_{22} +d'_{20}
\end{cases}}$



У другій системі умов нам відомі лише значення величин $d'_{10} ,d'_{20}$. Для того, щоб знайти $D'_{1} ,D'_{2}$ ми будемо додержуватися припущення, що  кількість спожитої галуззю продукції  своєї чи іншої галузі (вхід) по відношенню до виготовленої продукції (вихід) залишається незмінною з року в рік, тобто: $$\dfrac{d'_{ij}}{D'_{j}} =\dfrac{d_{ij}}{D_{j}}.$$

Наприклад, якщо цього року спожита сталь для автопромисловості (вхід) відносилася до виготовленої автопромисловістю продукції (вихід) як  $d_{12}/D_2=2664/30346$, то таким самим буде співвідношення $d'_{12}/D'_2$ й на наступний рік.

З припущення виразіть величини $d'_{ij}$ та підставте в другу систему. Також підставте значення $d' _{10} ,d'_{20}$. Має залишитися система рівнянь з двома невідомими $D'_{1} ,D'_{2}$.

✔️ *Ваші міркування запишіть тут.*

Запишіть матрицю системи, її праву частину, та розв'яжіть систему, щоб знайти  $D'_1, D'_2$.

In [ ]:
#write your code here

Зробіть спостереження: чи вірно, що виробництво сталі ($D'_1$) зросло на величину $\Delta_1$, а виробництво авто ($D'_2$) зменшилося на величину $\Delta_2$? Як змінилися ці величини порівняно з попереднім роком? Чи можете Ви висловити припущення, чому так сталося?

✔️ *Ваші міркування запишіть тут.*

2️⃣ Узагальніть ідею такого аналізу на довільну кількість окремо розглянутих галузей: $B_1, B_2, \dots , B_n$ та зовнішніх споживачів ('other consumption').
Вважайте, що вам задано вектор загального виробництва (і споживання) $D = (D_1, \dots , D_n)$, матрицю споживання галузями $(d_{ij})$ на цей рік, а також вектор прогнозів змін у споживанні зовнішніми споживачами на наступний рік $\Delta = (\Delta_1, \dots, \Delta_n)$, такий що $d'_{i0}=d_{i0}+\Delta_i$. Напишіть програму, яка розраховує вектор виробництва за галузями на наступний рік: $D' = (D'_1, \dots , D'_n)$.

In [ ]:
#write your code here

Протестуйте вашу функцію зокрема на наступній матриці статистики виробництва-споживання за трьома галузями (наприклад, 'сільське господарство', 'залізниця', 'морські перевезення') і векторі змін зовнішнього споживання $\Delta = (625, 200, 475)$

In [ ]:
df_economy_test = pd.DataFrame(columns = ['branch', 'B1_consumption', 'B2_consumption','B3_consumption' ,'other_consumption', 'total'])
df_economy_test['branch'] = ['B1', 'B2', 'B3']
df_economy_test['B1_consumption'] = [25,  25, 15]
df_economy_test['B2_consumption'] = [50,  50, 10]
df_economy_test['B3_consumption'] = [100, 50, 0]
df_economy_test['other_consumption'] = ['', '', '']
df_economy_test['total'] = [800, 300, 500]
df_economy_test

branch  B1_consumption  B2_consumption  B3_consumption other_consumption  \
0     B1              25              50             100                     
1     B2              25              50              50                     
2     B3              15              10               0                     

   total  
0    800  
1    300  
2    500

<font color="red"> *Коментар викладача:* <font>

🧩 **2.2. Кубічні сплайни**

У цій задачі ми будемо розв'язувати задачу інтерполяції кубічними сплайнами, а саме будувати гладкі функції, що набувають певних значень в певних точках і при цьому
на ділянках своєї області визначення задаються як многочлени -- різні на різних ділянках, але дуже добре узгоджені.

Як відомо, задача про інтерполяційний многочлен полягає в тому, щоб за заданими значеннями многочлена в певних точках відновити цей многочлен.
Також відомо (погортайте свій конспект з алгебри за перший семестр, або дивіться тут https://en.wikipedia.org/wiki/Polynomial_interpolation), що
за множиною $n+1$ точок вигляду $(x_i, y_i)$ можна однозначно відновити многочлен $f(x)$ степеня $n$ або менше, такий що $f(x_i)=y_i$ -- так званий інтерполяційний многочлен.

Але, зазвичай, якщо точок багато, то поведінка інтерполяційного многочлена не відповідає очікуванням поза тими точками, через які він має проходити.
Це так званий ''феномен Рунге''. Кажуть, що інтерполяційний многочлен осцілює поза тими точками, через які  проходить. Такий ефект спостерігається для інтерполяційних многочленів великого степеня.
Побачити це можна на наступному прикладі: ми намагаємося наблизити многочленом 10-го степення функцію $f(x)=\dfrac{1}{1+25x^{2}}$. Побудований многочлен, звісно, проходить через вказані точки, але не схожий на функцію, що він її має наближати, між точками, особливо на краях.

<img src='https://github.com/LPolyakova/Linear_Algebra_for_CS_students/blob/main/CP/images/Interpolation_runge_funktion.png?raw=1' width=320, heigth=240>

Виходом є метод, у якому ми наближаємо функцію за шматками многочленами невеликого степеня, наприклад, третього. Кожен з таких многочленів задано на відрізку, при цьому у точках 'стику' многочлени узгоджені (див. https://en.wikipedia.org/wiki/Spline_interpolation), так щоб функція, визначена на сукупності усіх заданих відрізків була гладкою. Такий підхід називається сплайновою інтерполяцією й виник з потреб проектування кузовів автомобілів, які добре обтікаються повітрям.

Побудуємо систему кубічних сплайнів, що проходять через систему точок $[(x_0,y_0), \dots, (x_n, y_n)]$.

Кубічний многочлен з номером $i$ буде задано на відрізку $[x_i, x_{i+1}]$ і на кінцях цього відрізку він має набувати значення  $y_i, y_{i+1}$ відповідно. Ми будемо подавати многочлен з номером $i$ у вигляді
$S_i=a_i+b_i(x-x_i)+c_i(x-x_i)^2+d_i(x-x_i)^3$ (тобто розкладати не за степенями  $x$, а за степенями $x-x_i$ -- так зручніше).

Для отримання суцільної гладкої функціі мають виконуватися наступні умови:

1. $S_i(x_i)=y_i; S_i(x_{i+1})=y_{i+1}, \quad (i=0,1,\dots, n-1)$, тобто умова інтерполяції -- функція проходить через усі задані точки, зокрема 'сусідні' многочлени мають однакові значення у точках 'стику'.

2. $S'_i(x_{i+1})=S'_{i+1}(x_{i+1})  \quad  (i=0,1,\dots, n-2)$, тобто рівність похідних --  умова гладкості у точках 'стику', гарантує, що ми не помітимо перехід від одного 'шматка' функціі до наступного неозброєним оком, перехід відбудеться гладко.

3. $S''_i(x_{i+1})=S''_{i+1}(x_{i+1})  \quad  (i=0,1,\dots, n-2)$, тобто рівність других похідних -- умова рівності кривизни зліва й справа у точках 'стику', гарантує, що перехід не лише відбудеться без зламів, але й плавно.

4. $S''_0(x_0)=0; S''_{n-1}(x_n)=0$, тобто умова нульової кривизни на кінцях відрізка -- для того, що побудовану функцію можна було 'приклеїти' ще до якоїсь за потреби.

1️⃣ Обчисліть похідні многочленів  $S_i$ й запишіть умови кубічних сплайнів у вигляді системи лінійних рівнянь відносно невідомих коефіцієнтів многочленів $a_i, b_i, c_i, d_i$.

✔️ *Ваші міркування запишіть тут.*

2️⃣ Напишіть функції, які за заданими точками $[(x_0,y_0), \dots, (x_n, y_n)]$

1. Знаходить матрицю системи умов для кубічних сплайнів.
2. Знаходить праву частину системи.
3. Розв'язує систему й знаходить коефіцієнти кубічних сплайнів.
4. За заданим масивом значень $x$ і коефіцієнтами кубічного многочлена $S$ обчислює значення цього многочлена у точках з масиву $x$.

In [ ]:
# write your code here

Зробіть візуалізацію отриманих результатів:

1. Задайте точки  $[(x_0,y_0), \dots, (x_n, y_n)]$.
2. Cформуйте масиви значень $x$ для кожного відрізка  $[x_i, x_{i+1}]$.
3. Обчисліть значення відповідного многочлена на цьому відрізку (у вас уже є для цього функція)
4. Намалюйте графіки многочленів на площині.

In [ ]:
# write your code here

Має вийти щось схоже на наступний малюнок. На ньому три сплайни, які проходять через точки $(1,2), (2,3), (4,1), (7, 4)$.
На кожному з відрізків $[1,2], [2,4], [4,7]$ функція є кубічним многочленом.

<img src='https://github.com/LPolyakova/Linear_Algebra_for_CS_students/blob/main/CP/images/Cubic_splines.png?raw=1' width=320, heigth=240>

3️⃣ Для цієї ж задачі використайте готову функцію  CubicSpline з бібліотеки scipy.interpolate.
Зробіть її візуалізацію. Порівняйте результати.

In [ ]:
from scipy.interpolate import CubicSpline
#write your code here

<font color="red"> *Коментар викладача:* <font>

## Задача 3: визначники

Оберіть і розв'яжіть одну із задач 3.1 або 3.2 на ваш вибір. Іншу задачу видаліть з шаблону.

🧩 **3.1. Вандермонд, Крамер та Лагранж**

Нагадаємо, що задача інтерполяції полягає в тому, щоб за заданими значеннями многочлена в певних точках відновити цей многочлен. Також відомо (погортайте свій конспект з алгебри за перший семестр, або дивіться тут https://en.wikipedia.org/wiki/Polynomial_interpolation), що
за множиною $n+1$ точок вигляду $(x_i, y_i)$ можна обнозначно відновити многочлен $p(x)$ степеня $n$, такий що $p(x_i)=y_i$ -- так званий інтерполяційний многочлен.

У цій задачі ми обговоримо цей результат з лінійноалгебраїчної точки зору.

1️⃣  Нехай ми шукаємо многочлен $p(x)$ у вигляді $p(x)=a_0+a_1x+\dots +a_nx^n$, де $a_0, a_1, \dots, a_n$ -- невідомі коефіцієнти.
Запишіть умови $p(x_i)=y_i$  підставивши $x_i$ до виразу для $p(x)$. Ви маєте отримати систему $n+1$ лінійних рівнянь. Запишіть її у матричному вигляді. Чи впізнали ви матрицю цієї системи? Поясніть, чому ця система має єдиний розв'язок за умови, що всі $x_i$ різні.


✔️ *Ваші міркування запишіть тут.*

2️⃣ У цій частині ми подивимося, як можна отримати інтерполяційний многочлен (це буде інтреполяційний многочлен у формі Лагранжа) у випадку $n=2$, а далі узагальнимо отриманий результат.

Нехай $x=(x_1, x_2, x_3)$, $y=(y_1, y_2, y_3)$ і $a=(a_0, a_1, a_2)$ -- шуканий вектор коефіцієнтів інтерполяційного многочлена.

Нехай $Aa=y$ -- лінійна система для пошуку $a$, що ви її отримали в попередньому пункті. Зазначимо, що якщо ми знайдемо розв'язки системи $a^1, a^2, a^3$ для $y=y^1=(1,0,0)$, $y=y^2=(0,1,0)$, $y=y^3=(0,0,1)$ відповідно, то для довільного $y=(y_1, y_2, y_3)$ отримаємо, що $a=y_1a^1+y_2a^2+y_3a^3$ є розв'язком системи  $Aa=y$, оскільки
$A(y_1a^1+y_2a^2+y_3a^3)=y_1\cdot Aa^1+y_2\cdot Aa^2+y_3\cdot Aa^3 = y_1y^1+y_2y^2+y_3y^3=y$.

Будь ласка, не заплутайтеся в індексах в цих записах: $a^1, a^2, a^3$, $y^1, y^2, y^3$, а також $a$ і $y$ -- це вектори, пронумеровані верхніми індексами (це саме верхні індекси, а не степені), а $a_0, a_1, a_2$ і $y_1, y_2, y_3$ -- скаляри.

За допомогою метода Крамера розв'яжіть системи  $Aa=y^1$, $Aa=y^2$, $Aa=y^3$. Ви можете розв'язати одну систему, а для двох інших виписати розв'язки за аналогією.

Далі випишіть загальний розв'язок для $n=2$, а саме $a=y_1a^1+y_2a^2+y_3a^3$. Чи впізнали ви в ньому інтерполяційний многочлен Лагранжа? Запишіть за аналогією вираз для інтерполяційного многочлена у випадку довільного $n$.

✔️ *Ваші міркування запишіть тут.*

3️⃣ Напишіть функцію, яка отримує на вхід $n+1$ пару чисел $(x_i, y_i)$ і на виході видає коефіцієнти інтерполяційного многочлена (не вище як) $n$-го степеня $f(x)$, такого що $f(x_i)=y_i$.

In [ ]:
#write your code here

<font color="red"> *Коментар викладача:* <font>

🧩 **3.2. Трюк Чіо**

У цій задачі ми розглянемо ще один рекурентий спосіб знаходження визначника. На відміну від способа "розкладання за рядком", який зводить обчислення визначника порядку $n$ до обчислення $n$ визначників порядку $n-1$, "трюк Чіо"(названий на честь італійського математика Фелікса Чіо, який запропонував його у статті. F. Chio. Memoire sur les fonctions connues sous le nom de resultantes ou de determinants. Turin: E. Pons, 1853), зводить обчислення визначника порядку $n$ до обчислення лише одного визначника порядку $n-1$, але такого, що його елементами є визначники порядку 2.

Ідею методу ми зрозуміємо на прикладі, в якому будемо обчислювати визначник

${\displaystyle \det A=\det\begin{pmatrix} 2 & 1 & 1\\ 3 & 4 & -1\\ 1 & 5 & 1 \end{pmatrix}}.$

Коли за допомогою методу Гаусса обчислюють цілочисельні визначники власноруч, то, зазвичай, намагаються уникати дробових елементів. Так, у цьому прикладі, ми можемо відняти від подвоєного другого рядка потроєний перший ($2II-3I$), і від подвоєного третього рядка відняти перший ($2III-I$), для того, щоб перетворити усі елементи першого стовпчика, окрім верхнього, на 0.

Вийде, що $\det A=\frac{1}{4}\det B$, де $B=\begin{pmatrix}
2 & 1 & 1\\
0 & 5 & -5\\
0 & 9 & 1
\end{pmatrix}$ (зрозумійте, звідки взялася $\frac{1}{4}$).

Зверніть увагу, що елементи матриці $B$ можна подати, як мінори матриці $A$, а саме
$\displaystyle b_{22} =\begin{vmatrix}
2 & 1\\
3 & 4
\end{vmatrix} ,\ b_{23} =\begin{vmatrix}
2 & 1\\
3 & -1
\end{vmatrix} ,\ b_{32} =\begin{vmatrix}
2 & 1\\
1 & 5
\end{vmatrix} ,\ b_{33} =\begin{vmatrix}
2 & 1\\
1 & 1
\end{vmatrix}$

1️⃣ Розберемося в загальному випадку (але поки що для визначників порядку 3), чому так відбувається.

Нехай $A=\begin{pmatrix}
a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23}\\
a_{31} & a_{32} & a_{33}
\end{pmatrix}$. Домножимо другий та третій рядок на $a_{11}$ (нехай  $a_{11}\ne 0$) і отримаємо матрицю $B=\begin{pmatrix}
a_{11} & a_{12} & a_{13}\\
a_{11}a_{21} & a_{11}a_{22} & a_{11}a_{23}\\
a_{11}a_{31} & a_{11}a_{32} & a_{11}a_{33}
\end{pmatrix}$, причому $\det B= a_{11}^2\det A$.

Виконайте такі перетворення рядків матриці $B$: $II-a_{21}I$, $III-a_{31}I$ і запишіть, яку матрицю $C$ ви отримали. Зазначимо, що $\det C=\det B= a_{11}^2\det A$.

Також зверніть увагу на те, що у другому та третьому рядках матриці $C$ стоять мінори матриці $A$. Які? Розкрийте визначник матриці $C$ за першим стовпчиком і отримайте, що $\det A = \frac{1}{a_{11}}\det D$, де матриця $D$ має порядок 2 і складається з чотирьох мінорів матриці $A$.

✔️ *Ваші міркування запишіть тут.*

2️⃣ Тепер доведіть цей результат у загальному випадку. А саме, нехай $A=(a_{ij})$ -- матриця порядку $n$, причому $a_{11}\ne 0$, а матриця $D=(d_{ij})$ порядку $n-1$ складається з елементів   $d_{ij} = \begin{vmatrix}
a_{11} & a_{1, j+1}\\ a_{i+1, 1} & a_{i+1, j+1} \end{vmatrix}$  (тобто мінорів другого порядку матриці $A$, які містяться  на перетині першого та $i+1$ рядків з першим та  $j+1$ стовпчиками).

Тоді $\det A = \frac{1}{a_{11}^{n-2}}\det D$.

Зрозуміло, що цей "трюк" діє не лише у випадку цілочисельних матриць (як це було у нашому першому прикладі), а й для матриць з довільними елементами.

✔️ *Ваші міркування запишіть тут.*

3️⃣ Наведіть ваші думки щодо того, як виконувати "трюк Чіо" у випадку, коли $a_{11}=0$.

✔️ *Ваші міркування запишіть тут.*

4️ Напишіть функцію, яка реалізує "трюк Чіо". Протестуйте вашу функцію. Порівняйте швидкодію цього способу обчислення визначника з іншими способами.

In [ ]:
#write your code here

<font color="red"> *Коментар викладача:* <font>